### ISSUE TITLE
Global - Lista de Fundaciones (View)

### ISSUE THREAD

**Issue by Jrocam** [verynice-solutions/Firulais-fire-native#2]
Un user tipo usuario/fundación verá en su Drawer "Fundaciones"

- [x] Poner item Fundaciones en el drawer y en las routes

**Data**
- [x] Action - Fetch fundaciones de db (/users)
- [x] Crear Reducer/InitialState Redux  (parecido a lo que está en currentUser)
- [x] MapStateToProps en la vista(reduxState)

**Style**
- [x] Componente de lista [ thumbnail - text - star ]
- [x] FlatList scroll vertical
- [ ] **Extra** {:star:} -> Search component en el header para filtrar las fundaciones por nombre.

- [x] **MEGA STAR** {:star::sparkles:} -> Do the same for Users

**Bugs**
- [x] Fix -  It dies when theres no profile object in one of the /users

**Comment by mateodaza** [comment]
Too lazy to do the Extra {⭐️}  :trollface: also heckin redux 😆

**Comment by Jrocam** [comment]
It dies when theres no profile object in one of the /users

**Comment by mateodaza** [comment]
oh no

**Comment by Jrocam** [comment]
osheme!
