### ISSUE TITLE
Servicios - Dates of status changes

### ISSUE THREAD

**Issue by Jrocam** [verynice-solutions/Firulais-fire-native#23]
Añadir fecha de aceptar/rechazar/etc al historial

**. . .Features**
- [x]  - Sent date to service db when service is created ⭐️ 
- [x]  - Sent date to service db when foundation acepta/rechaza ✨ 
- [x]  - Sent date to service db when foundation progreso/finaliza ⭐️ ✨  
- [x]  - Sent date to service db when calification completes ⭐️

**Comment by mateodaza** [comment]
another one bites the dust
