### ISSUE TITLE
Ratings - Promedio calificaciones

### ISSUE THREAD

**Issue by Jrocam** [verynice-solutions/Firulais-fire-native#26]
Calcular promedio de calificaciones de servicios finalizados y ponerlo en el profile del user y en su drawer.

**. . .Features**
- [x]  - Calcular el promedio apenas el user inicia sessión ( meter en redux? )  ⭐️ ✨ 
- [x]  - Mostrar calificación promedio en drawer  ✨ 
- [x]  - En el perfil del usuario poner calificación { cute styling earns ✨MEGASTAR⭐️ )

**Comment by mateodaza** [comment]
It's solved so far without redux, no reason to update it if it is not listening to the changes from the back

**Comment by mateodaza** [comment]
For future enhancements, it would be nice for the back to retrieve all user's relevant info and for redux to keep track on updates
