### ISSUE TITLE
Profile Fundación (View)

### ISSUE THREAD

**Issue by Jrocam** [verynice-solutions/Firulais-fire-native#3]
This is worth like **5 stars** {:star::sparkles::star::star::sparkles:}
Esta es la lista que ve el usuario cuando la encuentra ya sea en lista de todas fundaciones, en Sus fundaciones , o desde una noticia hecha por dicha fundación. 

**Data**
- [x] Action - Fetch fundación info de db (/users/fundationID)
- [x] Action - Fetch mascotas de fundación de db (/pets)
- [x] Action - Fetch news de esa fundación de db (/news)

**Style**
- [x] Header - Con foto central
- [x] Header - Descripción debajo de foto
- [x] Mascotas - Item de la lista CardStyle, [Foto - name]
- [x] Mascotas - FlatList con scroll horizontal 
- [x] Mascotas - "ver más.." button debajo de la lista
- [x] News - Item de la lista [thumbnail - description - icon]
- [x] News - FlatList con scroll horizontal 
- [x] News - "ver más.." button debajo de la lista

**MEGA STAR** {:star::sparkles:}-> grab this and do the same for persons aka issue #4 
**Bugs**
*no bugs yet*

**Comment by mateodaza** [comment]
I guess it was done a long time ago. blep
