### ISSUE TITLE
Profile Usuario (View)

### ISSUE THREAD

**Issue by Jrocam** [verynice-solutions/Firulais-fire-native#4]
Esta es la vista que puede ver cualquier tipo de user en "lista de todos los usuarios" o una fundación la encuentra en "Mis voluntarios"...

**Data**
- [x] Action - Fetch user info de db (/users/userId)
- [x] Action - Fetch Info fundaciones a las que el usuario es voluntario de db (/users)
- [x] Action - Fetch feedback objects con userID de db (/feedbacks)

**Style**
- [x] Header - Foto central
- [x] Header - Descripción debajo de foto
- [x] Fundaciones - Item de la lista BadgeStyle, [Thumbnail - name]
- [x] Fundaciones - FlatList con scroll horizontal 
- [x] Fundaciones - "ver más.." button debajo de la lista ( lo manda a todas las fundaciones view)
- [x] Feedbacks - Item de la lista [ThumbnailFundacion - NombreServicio - textoFeedback - puntuación:star: ]
- [x] Feedbacks - FlatList scoll vertical

**Bugs**
*no bugs yet*

**Comment by Jrocam** [comment]
> vertical

i

**Comment by mateodaza** [comment]
yappp
