### ISSUE TITLE
Solicitudes (View)

### ISSUE THREAD

**Issue by Jrocam** [verynice-solutions/Firulais-fire-native#5]
Servicios que la fundación tiene pendientes por aprobar/rechazar sobre el cuidado/adopción de una mascota. Es una Lista, así como las fundacionsList y cada item abre un modal ( ver mockup )
Entra - clickando en el drawer ó clickando en la card "Revisar Solicitudes" en el homeFundation.

to be continue...
**Data**
- [x]  **MEGA STAR** {:star::sparkles:} -> Firebase - Crear/Cranearse el mock data en la db ( ver diagrama clases en drive )
- [x] Action -Create del servicio en la db cuando se pide un doggo /services/serviceID estado:'pendiente', petInfo:{object}
- [x] Action - Fetch servicios activos de db /services with {estado:'pendiente'} para cada fundación
- [x] Action - Update estado/feedback del servicio en la db cuando se acepta/rechaza (/services/serviceID {estado:'aprobado/rechazado'} ) 

**Style**
- [x] Componente de lista [ thumbnail(pet) - text(infoPet) - (fundación/user info) ]
- [x] FlatList scroll vertical 
- [x] Open Modal onPress item of the list [With all info (PetInfo, feedBackInfo)]

**Bugs**
-*no issues yet*

**Comment by Jrocam** [comment]
Amazing stuff!

**Comment by mateodaza** [comment]
🐶
