### ISSUE TITLE
Fundación - Añadir Mascota (View)

### ISSUE THREAD

**Issue by Jrocam** [verynice-solutions/Firulais-fire-native#6]
Hacer que una fundation pueda añadir mascoteishion
- [x] Para poder añadir fotos desde galería y camara hay que pedirle los permisos adecuados al user apenas inicie sesión ( https://docs.expo.io/versions/v27.0.0/sdk/permissions ) [doesn't work on simulator]

**. . .Enhance:**
- [x] Style cutiefy on the view{ ✨ ⭐️} 

**Data**
- [x] Manage states better in the view 
- [x] Quitar foto añadida al array

to be continue...

**Bugs**
- [x] Archivos de la camara se añaden incorrectamente

**Comment by mateodaza** [comment]
⭐️
