### ISSUE TITLE
Inicio de sesión

### ISSUE THREAD

**Issue by varepato** [verynice-solutions/Firulais-fire-native#8]
Cambiar ventana de inicio de sesión.
- [x] Colocar solo un botón para iniciar sesión.

Primera vez del inicio de sesión:
- [x] El campo {type} del usuario esta null.
- [x] Mostrar un botón de cada tipo de usuario. 
- [x] Al hacer click en el botón de tipo, guardar el tipo y los datos de usuario en firebase. 

El usuario ya ha iniciado sesión por primera vez:
- [x] Verificar en firebase que tipo de usuario es.
- [x] Pasar directamente a la vista correspondiente al tipo del usuario.

**Comment by Jrocam** [comment]
Done this! yisus

**Comment by Jrocam** [comment]
Veri closing solution !
